### PR TITLE
Fix size of output

### PR DESCRIPTION
**Pull request by imagejan**
In order to get a FinalInterval with `min=min` and `max=max`, we have to create it with `dims = max - min + 1`.

See https://github.com/knime-ip/knip/issues/499.

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks!

**Comment by ctrueden** [comment]
I cut the imagej-deprecated 0.1.5 release including this fix. The [build](https://travis-ci.org/github/imagej/imagej-deprecated/builds/749116261) is still pending.

**Comment by imagejan** [comment]
@ctrueden the build just passed, but due to missing `<ciManagement>` definition in the POM, didn't get deployed.

**Comment by ctrueden** [comment]
It isn't a missing `ciManagement`, but rather something about accessing the pom-scijava parent from the remote repository. Strange. I'm investigating.

**Comment by imagejan** [comment]
You're right. Indeed, maven.scijava.org currently only lists a few JitPack versions of `pom-scijava`:

https://maven.scijava.org/#nexus-search;gav~org.scijava~pom-scijava

... but this exists:

https://maven.scijava.org/content/groups/public/org/scijava/pom-scijava/29.2.1/

**Comment by ctrueden** [comment]
Version 0.1.5 is deployed now. All I did was rerun the Travis tag build, and this time it worked. 🤷

**Pull request merged**
